### PR TITLE
Create index.html

### LINKED ISSUE #5: Sample issue by the maintainer
* short-term goals of the project divided into issues using checkmarks [x]
* long term goals broken u into several issues
* be clear about the problem statement
* documentation, minor no-code issues as well

### PR DESCRIPTION
**Pull request by yashraj-02-techie**
closes #5 
fixes #1

### CODE REVIEW

**Comment by akshitadixit** [comment]
why even

**Comment by akshitadixit** [comment]
have a look at the edit

**Review by akshitadixit — APPROVED** [review]
lgtm

**Review by Akshit17 — COMMENTED** [review]
Nice boilerplate

**Review by Akshit17 — APPROVED** [review]

**Review by Akshit17 — APPROVED** [review]

**Pull request merged**
